version: 2.7.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2022
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  verbosity: minimal
configuration: Release
install:
  - ps: mkdir -Force ".\build\" | Out-Null
before_build:
- ps: nuget restore
build_script:
- ps: '& .\Build.ps1'
test:
  assemblies:
    only:
      - '**\*Swashbuckle.dll'
artifacts:
- path: artifacts/Unchase.*.nupkg
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: Unchase.Swashbuckle.AspNetCore.Extensions-v$(appveyor_build_version)
  auth_token:
    secure: 5YjB5tKbw0Z/mnSTKxo3WLD9TWuyGpGPhaNlSTA+cFA1oORUk46i6tPuyvekHaS9
  repository: unchase/Unchase.Swashbuckle.AspNetCore.Extensions
  artifact: /Unchase.*\.nupkg/
  on:
    branch: master                # release from master branch only
    appveyor_repo_tag: false      # deploy on tag push only
- provider: NuGet
  api_key:
    secure: cGT8iq7VTgscsUD26dbL8WYNzfytfoIuiTCxEaMHGJ+KoIZNM8447EzOP37JIoiK
  skip_symbols: true
  artifact: /Unchase.*\.nupkg/
  on:
    branch: master                # release from master branch only
    appveyor_repo_tag: false      # deploy on tag push only
notifications:
- provider: Email
  to:
    - spiritkola@hotmail.com
  subject: 'Unchase.Swashbuckle.AspNetCore.Extensions - Build {{status}}'
  message: "Building complete, commitId = {{commitId}}"
  on_build_status_changed: true